LIBNAME ANL317G "C:/Users/SASUser25/Documents/GBA";
DATA ANL317G.StockQ12;
INFILE "C:/Users/SASUser25/Documents/GBA/StockPriceB_RawT2.csv" DLM="," FIRSTOBS=2;
INPUT Date DDMMYY10. Close;
FORMAT Date DDMMYY10.;
RUN;
PROC UNIVARIATE DATA=ANL317G.StockQ12 NORMAL PCTLDEF=4;
	VAR Close;
	QQPLOT Close;
RUN;
PROC TIMESERIES DATA=ANL317G.StockQ12 PLOTS=(acf pacf);
	ID Date INTERVAL=month ACCUMULATE=average;
	VAR Close;
RUN;
PROC SGPLOT DATA=ANL317G.StockQ12 NOBORDER;
	SERIES X=Date Y=Close / MARKERATTRS=(SIZE=5) LINEATTRS=(Colour=Green);
	REG X=Date Y=Close / LINEATTRS=(THICKNESS=2) 
	MARKERATTRS=(SIZE=1);
RUN;
PROC SGPLOT DATA=ANL317G.StockQ12 NOBORDER;
	VBOX Close;
RUN;
PROC SGPLOT DATA=ANL317G.StockQ12 NOBORDER;
	HISTOGRAM Close / NBINS=20;
	DENSITY Close;
RUN;
PROC TIMESERIES DATA=ANL317G.StockQ12 PLOTS=(decomp);
	ID Date INTERVAL=month;
	VAR Close;
RUN;
PROC TIMESERIES DATA=ANL317G.StockQ12 PLOTS=(all);
	ID Date INTERVAL=month;
	VAR Close;
RUN;
PROC EXPAND DATA=ANL317G.StockQ12 OUT=ANL317G.StockQ12_ma
	PLOTS=TRANSFORMOUT;
	ID Date;
	CONVERT Close = StockQ1_ma3 / TRANSOUT=(cmovave 3);
	CONVERT Close = StockQ1_ma5 / TRANSOUT=(cmovave 5);
	CONVERT Close = StockQ1_ma7 / TRANSOUT=(cmovave 7);
RUN;
PROC ARIMA DATA=ANL317G.StockQ12 OUT=ANL317G.StockQ12_maFC;
	IDENTIFY VAR=Date;
	ESTIMATE p=(1 2 3) ar=(0.33 0.33 0.33) NOINT NOEST
	NOSTABLE METHOD=CLS;
	FORECAST LEAD=12;
RUN;
PROC ESM DATA=ANL317G.StockQ12 OUTFOR=ANL317G.StockQ12_ses 
	PLOT=forecasts;
	ID Date INTERVAL=MONTH;
	FORECAST Close / Model=Simple;
RUN;
PROC ESM DATA=ANL317G.StockQ12 OUTFOR=ANL317G.StockQ12_des 
	PLOT=forecasts;
	ID Date INTERVAL=MONTH;
	FORECAST Close / Model=Double;
RUN;
PROC ESM DATA=ANL317G.StockQ12 OUTFOR=ANL317G.StockQ12_awin 
	PLOT=Forecasts;
	ID Date INTERVAL=MONTH;
	FORECAST Close / Model=addwinters;
RUN;
PROC ESM DATA=ANL317G.StockQ12 OUTFOR=ANL317G.StockQ12_mwin 
	PLOT=forecasts;
	ID Date INTERVAL=MONTH;
	FORECAST Close / Model=winters;
RUN;

PROC ESM DATA=ANL317G.StockQ12 OUTFOR=ANL317G.StockQ12_ses 
	PLOT=forecastspnly lead=12;
	ID Date INTERVAL=MONTH;
	FORECAST Close / Model=Simple;
RUN;
PROC ESM DATA=ANL317G.StockQ12 OUTFOR=ANL317G.StockQ12_des 
	PLOT=forecastspnly lead=12;
	ID Date INTERVAL=MONTH;
	FORECAST Close / Model=Double;
RUN;
PROC ESM DATA=ANL317G.StockQ12 OUTFOR=ANL317G.StockQ12_awin 
	PLOT=forecastspnly lead=12;
	ID Date INTERVAL=MONTH;
	FORECAST Close / Model=addwinters;
RUN;
PROC ESM DATA=ANL317G.StockQ12 OUTFOR=ANL317G.StockQ12_mwin 
	PLOT=forecastspnly lead=12;
	ID Date INTERVAL=MONTH;
	FORECAST Close / Model=winters;
RUN;
